repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        exclude: ^\.yamllint$|^\.github/workflows/

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  # - repo: https://github.com/ansible/ansible-lint
  #   rev: v24.7.0
  #   hooks:
  #     - id: ansible-lint
  #       files: ^infra/ansible/
  #       additional_dependencies:
  #         - "ansible>=9"

  # ↓↓↓ Заменили mirrors-prettier на локальный prettier --check
  - repo: local
    hooks:
      - id: prettier-check
        name: prettier --check
        language: system
        pass_filenames: false
        entry: bash -lc 'npx --yes prettier --check "app/**/*.{ts,tsx,js,jsx,json,css}" "**/*.{yml,yaml,md,json}"'
