name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: app/package.json
      - name: Inject Vite env from secrets
        run: echo "VITE_API_BASE_URL=${{ secrets.API_BASE_URL }}" >> $GITHUB_ENV
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: app/dist
