name: pre-commit
permissions:
  contents: read
on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python + pre-commit
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pre-commit

      # Node для mirrors-prettier (prettier ставится в изолированное окружение, но Node нужен)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Terraform для terraform_fmt/validate
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Всё остальное подтянется как additional_dependencies из .pre-commit-config.yaml
      - run: pre-commit run --all-files
