name: Infra Scans
on:
  pull_request:
  push:
    branches: [main]
jobs:
  terraform-validate:
    name: Terraform validate + tfsec + checkov
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - run: terraform init -input=false
      - run: terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra/terraform
      - name: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform
          quiet: true

  ansible-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/ansible
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible + ansible-lint
        run: |
          python3 -m pip install --upgrade pip
          pip install 'ansible>=9' ansible-lint
      - name: Run ansible-lint
        run: ansible-lint site.yml
